"use client";

import Sidebar from "@/components/Sidebar";
import ReelCard from "@/components/ReelCard";

interface Reel {
  id: number;
  script_text: string | null;
  caption: string | null;
  hashtags: string | null;
  video_url: string | null;
  status: string;
  buffer_post_id: string | null;
  target_platforms: string[];
  scheduled_at: string | null;
  posted_at: string | null;
  created_at: string;
  updated_at: string;
}

export default function DashboardClient({ reels }: { reels: Reel[] }) {
  return (
    <div className="flex min-h-screen bg-[#0a0a0f]">
      <Sidebar />
      <main className="flex-1 p-8 overflow-auto">
        <div className="max-w-7xl mx-auto">
          <div className="mb-8">
            <h1 className="text-2xl font-bold text-white">Reels</h1>
            <p className="text-gray-500 text-sm mt-1">
              {reels.length} total reels
            </p>
          </div>

          {reels.length === 0 ? (
            <div className="text-center py-20">
              <div className="text-gray-600 mb-4">
                <svg className="w-16 h-16 mx-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
              </div>
              <p className="text-gray-500">No reels yet. They will appear here once generated by n8n.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {reels.map((reel) => (
                <ReelCard key={reel.id} reel={reel} />
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
